name: ESP-IDF Build

permissions:
  contents: read
  pull-requests: write

on:
  push:
  pull_request:
  merge_group:
  schedule:
    - cron: "0 5 * * 3"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        idf_ver: [release-v5.4, latest]
        idf_target: [esp32c3, esp32h2, esp32s3, esp32p4]

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Delete CMakeLists.txt in components (only used for simulator build)
        run: rm components/CMakeLists.txt

      - name: ESP-IDF build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ matrix.idf_ver }}
          target: ${{ matrix.idf_target }}
          command: idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.release" build
